# Generated by Django 2.0.7 on 2018-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_auto_20180801_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
