# Generated by Django 2.0.7 on 2018-08-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0003_todolist_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='finish',
            new_name='finished',
        ),
    ]
